# Navigation Bar Links
#   The weight parameter defines the order that the links will appear in.

[[main]]
    name = "Blog"
    url = "/blog/"
    weight = 1
[[main]]
    name = "FOSS4G|2024"
    url = "https://2024.foss4g.org"
    weight = 2
