# Navigation Bar Links
#   The weight parameter defines the order that the links will appear in.

[[main]]
    name = "Blog"
    url = "/blog/"
    weight = 1
[[main]]
    name = "Tutorials"
    url = "/start/"
    weight = 2
[[main]]
    name = "Wiki"
    url = "https://wiki.osgeo.org/wiki/Brasil"
    weight = 3
